### ISSUE TITLE
Code templates do not wrap or scroll

### ISSUE THREAD

**Issue by EddieMachete** [rick-hansen-institute/ui#6]
The code templates in the mardown text expand in with as long as the longest line of code in them.  I suggest `overflow-x` is added to the `<pre>` elements so that the text does not run to long.  It is causing issues particularly on mobile, where horizontal scrolling is being required.

```css
pre {
    overflow-x: auto;
    padding-bottom: 16px;
}
```
